name: releases ci/cd

on:
  push:
    tags:
      - "v*.*.*"
      - "test-v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Tauri CLI
        run: bun add -d @tauri-apps/cli

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev \
            libglib2.0-dev \
            pkg-config

      - name: Build Tauri app
        run: bunx tauri build

      - name: Upload ${{ matrix.os }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            desktop/src-tauri/target/release/bundle/**/*.AppImage
            desktop/src-tauri/target/release/bundle/**/*.dmg
            desktop/src-tauri/target/release/bundle/**/*.msi
            desktop/src-tauri/target/release/bundle/**/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest
          path: artifacts/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest
          path: artifacts/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest
          path: artifacts/windows

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/linux/**/*.{AppImage}
            artifacts/macos/**/*.{dmg}
            artifacts/windows/**/*.{exe,msi}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # repository secret
